### ISSUE TITLE
Make name of data layer object editablw

### ISSUE THREAD

**Issue by nickyreinert** [toniarndt/datalayer-helper#1]
If I want to implement this library into an existing project, I need to be able to access and edit the name of the data layer object. Please add an optiont that allows me to change the name of the data layer to e.g. window.dataLayer, window.digitalData or similar. 

(Also please add the information to the doc, where the current data layer is stored)

**Comment by toniarndt** [comment]
New function `useDatalayer()` has been added. Please see the documentation.
https://github.com/toniarndt/datalayer-helper/blob/main/docs/README.md#usedatalayer

Documentation for "Where is the data stored?" has also been added.
https://github.com/toniarndt/datalayer-helper/blob/main/README.md#where-is-the-data-stored
